# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yet another blog
tagline:          Passionate about technology.
description:      Yet another blog about technology.
url:              http://blog.sleepmail.com

author:
  name:           'Anonymous'
  url:            https://blog.sleepmail.com

paginate:         1

# Custom vars

